server:
  port: 8769
spring:
  application:
    name: @pom.artifactId@
  security:
    user:
      name: "admin"
      password: "admin"
  mail:
    host: smtp.163.com
    username: liudaisu@163.com
    password: a313340196?
  boot:
    admin:
      notify:
        mail:
          to: 249519637@qq.com

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true #是否显示IP
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


