server:
  port: 8082
spring:
  application:
    name: @pom.artifactId@
  boot:
    admin:
      url: http://localhost:8769

#base serv cofig
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false

feign:
  hystrix:
    enabled: true

#redis:
#  limit: 5