server:
  port: 9004

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS